### ISSUE TITLE
Support for variable names longer than 8 chars

### ISSUE THREAD

**Issue by cjmcdonn** [tiamo/spss#10]
My variable names are being trimmed to 8 chars, causing numerous duplicate variable names. It seems this 8 char limit is coded pretty deeply into the project ( `$buffer->writeString($this->name, 8);` ).

Is there a flag or setting that I am missing to extend the name length to 64 chars (available since SPSS version 12)?

If it will require code changes could you give a high-level summary of the implications and scope of making this change?

Thanks for you time!

**Comment by markosko** [comment]
Problem is that `$this->name` is really 8 chars width, but full name is written in info property of reader so you can combine that info property with short var name `$reader->info[13]->data[$var->name]` but it will only exists if there more than 8 chars variable name
