### ISSUE TITLE
Cannot open file in SPSS with 2 variables

### ISSUE THREAD

**Issue by pcholewa** [tiamo/spss#12]
Hi!

When save file with below config, i cannot open saved file in SPSS - application hangs.

BUT, saved file opens success when:

-remove all variable 1 or 2
**OR**
-remove "width" from first variable
**OR**
-remove "values" from second variable

Anyone can help me? What i do wrong?

My code:
$writer = new \SPSS\Sav\Writer([
            'header' => [
                'prodName'     => '@(#) ' . $this->analysis->getName(),
                'layoutCode'   => 2,
                'compression'  => 1,
                'weightIndex'  => 0,
                'creationDate' => date('Y-m-d'),
                'creationTime' => date('H:i:s'),
            ],
            'variables' => [
                [
                    'name' => 'aaa',
                    'width' => 16,
                    'format' => 1,
                ],
                [
                    'name' => 'cc',
                    'format' => 5,
                    'values' => [
                        1 => 'Panel',
                    ]
                ],
            ]
        ]);
        $pathFile = 'spss.sav';
        $writer->save($pathFile);

**Comment by tiamo** [comment]
Hi! Have you tried without compression ?

**Comment by pcholewa** [comment]
without compression still does not work, any more idea?

**Comment by pcholewa** [comment]
Probably it's something wrong with writer. When i open saved (with writer) file, there are difference in array of variables - precisely in "print" and "write".
Additionally, when (in above code) i reverse order of variables it's open successfully in SPSS.

Can You check that? I would be very grateful :)

**Comment by tiamo** [comment]
> Probably it's something wrong with writer. When i open saved (with writer) file, there are difference in array of variables - precisely in "print" and "write".
> Additionally, when (in above code) i reverse order of variables it's open successfully in SPSS.
> 
> Can You check that? I would be very grateful :)

I have released new version 2.1.0, try to update and check.

**Comment by pcholewa** [comment]
Unfortunately don't work. Have you try save .sav with example of my first post?

**Comment by tiamo** [comment]
@pcholewa try again, I have updated the code.

**Comment by pcholewa** [comment]
It works! Thank You very much!

**Comment by pcholewa** [comment]
reopen, after last changes you apply this issue not working. Can You check that?

**Comment by pcholewa** [comment]
sorry, my fault, Your current 2.1.0 version not working, last changes from dev-master#cc710d53358f5b1f4ad9626cb21608c78ab09336 works fine!

**Comment by tiamo** [comment]
done
