### ISSUE TITLE
Trimmed label and variables texts

### ISSUE THREAD

**Issue by pcholewa** [tiamo/spss#15]
Hi again!

When I set PL chars in the label of variable or text in values in a variable, saved .sav file in SPSS have trimmed text.

Example, when i set:
`$variable->label = 'Data zakończenia';`
In SPSS i got label "Data zakończeni".

This same is when I set example:
`$variable->values = [
            1 => 'Kobieta',
            2 => 'Mężczyzna'
        ];`
In SPSS i got "Mężczyzn" rather then "Mężczyzna"

Can You check this?

**Comment by mennodekker** [comment]
I did not fix the value labels, only the variable label. The fix is probably something similar like I did for the variable label.
