### ISSUE TITLE
chinese is mojibake in the generated file

### ISSUE THREAD

**Issue by buyPcToJJboom** [tiamo/spss#20]
When I set valuelabel, variablelable and data in Chinese, the value of the field in the sav file is Mojibake.
![image](https://user-images.githubusercontent.com/30775855/53613134-0b67b500-3c10-11e9-9437-cde417865419.png)

![image](https://user-images.githubusercontent.com/30775855/53613235-68636b00-3c10-11e9-84fe-d90e51931918.png)

**Comment by buyPcToJJboom** [comment]
`
$writer = new \SPSS\Sav\Writer([
    'header' => [
        'prodName' => '@(#) IBM SPSS STATISTICS 64-bit Macintosh 23.0.0.0',
        'creationDate' => '05 Oct 18',
        'creationTime' => '01:36:53',
        'weightIndex' => 0,
    ],
    'variables' => [
        [
            'name' => 'test1',
            'format' => Variable::FORMAT_TYPE_F,
            'width' => 4,
            'decimals' => 2,
            'label' => 'test',
            'values' => [
                1 => '1测试中文标签1',
                2 => '2测试中文标签2',
            ],
            // 'missing' => [],
            'columns' => 5,
            'alignment' => Variable::ALIGN_RIGHT,
            'measure' => Variable::MEASURE_SCALE,
            'attributes' => [
                '$@Role' => Variable::ROLE_PARTITION,
            ],
            'data' => [1, 1, 1],
        ],
        [
            'name' => 'test2',
            'format' => Variable::FORMAT_TYPE_A,
            'width' => 100,
            'label' => 'test',
            'columns' => 100,
            'alignment' => Variable::ALIGN_LEFT,
            'measure' => Variable::MEASURE_NOMINAL,
            'attributes' => [
                '$@Role' => Variable::ROLE_SPLIT,
            ],
            'data' => ['测试中文数据1', '测试中文数据2', '测试中文数据3'],
        ],
    ],
]);
`

**Comment by tiamo** [comment]
I'll check it as soon as possible.

**Comment by buyPcToJJboom** [comment]
I think the problem is on line 249.

https://github.com/tiamo/spss/blob/a17eb3a9acc49aeb0db7d5f5998ffe492d00ecb6/src/Sav/Record/Data.php#L247-L256

**Comment by mennodekker** [comment]
Line 249: 
$val = substr($value, $offset, 8);

That seems to do the trick for me. At least in spss the data looks the same. This probably goes for other parts of the code as well. The catch is that we do not chop chars that can be 1, 2 or 3 bytes but really segments of 8 bytes. I also tried mb_strcut but ended up having spaces between the segments.

**Comment by mennodekker** [comment]
![chinese](https://user-images.githubusercontent.com/922643/53792610-5f360f00-3f2c-11e9-863d-b6baf15bdc6c.PNG)

**Comment by mennodekker** [comment]
I will push a fix with unit test later

**Comment by buyPcToJJboom** [comment]
> Line 249:
> $val = substr($value, $offset, 8);
> 
> That seems to do the trick for me. At least in spss the data looks the same. This probably goes for other parts of the code as well. The catch is that we do not chop chars that can be 1, 2 or 3 bytes but really segments of 8 bytes. I also tried mb_strcut but ended up having spaces between the segments.

https://github.com/tiamo/spss/blob/a17eb3a9acc49aeb0db7d5f5998ffe492d00ecb6/src/Sav/Record/Data.php#L249-L255

line 249 $val = mb_substr($value, $offset, 8);  Is 8 characters, may be more than 8 bytes
line 254 buffer writeString method

https://github.com/tiamo/spss/blob/a17eb3a9acc49aeb0db7d5f5998ffe492d00ecb6/src/Buffer.php#L205-L220

line 219 The first argument of pack, 'A' . $length , length seems to be byte length
