### ISSUE TITLE
SPSS Crashes For String Variables Longer Than 255 Characters

### ISSUE THREAD

**Issue by jrking4** [tiamo/spss#24]
The library is working great for me. However it appears that whenever I try to define a FORMAT_TYPE_A (string) variable with a width of over 255 characters, the SAV file does not open and crashes SPSS.   

SPSS should support strings up to 32767 characters.
https://www-01.ibm.com/support/docview.wss?uid=swg21476969

**Comment by mennodekker** [comment]
See #30

**Comment by mennodekker** [comment]
@jrking4 Can you check with latest release https://github.com/tiamo/spss/releases/tag/2.1.5 if this problem is fixed and share your experience here?

**Comment by jrking4** [comment]
Just pulled the latest commit down and still get a freeze/crash from SPSS

**Comment by mennodekker** [comment]
Could you provide a (minimal) example of code that freezes/crashes? The unit tests are running (see https://github.com/tiamo/spss/blob/master/tests/LongStringTest.php ) and I get no problems at the moment so if you could provide a sample that would really help to understand and possibly fix your problem.

**Comment by meletis** [comment]
The output of LongStringTest doesn't work for me weither. SPSS will give me errors when I go to the Data view and the data are replaced with question marks:

![image](https://user-images.githubusercontent.com/654163/62132433-bd9dc880-b2e5-11e9-915e-23bb2dd7c70d.png)

**Comment by meletis** [comment]
I found a bug for very long texts when bytecode compression is not enabled. Could that be the case?

#39

**Comment by tiamo** [comment]
fixed
