### ISSUE TITLE
SPSS crashes

### ISSUE THREAD

**Issue by dannyboyng** [tiamo/spss#3]
I found a bug in the library.

When you look at the demo from test_write.php and switch the Numeric and String codeblocks. So create strings vars first and then create numeric vars. SPSS will crash when trying to open the .sav file.

**Comment by dannyboyng** [comment]
Btw I'm using SPSS version 21

**Comment by frodopopodo** [comment]
GREAT Library, but i found the same bug :-(( SPSS can't read the file when you add a numeric variante AFTER adding a string variable...

**Comment by tiamo** [comment]
i fixed bug
