### ISSUE TITLE
SPSS can't open files that have a variable with a width of 256 or greater.

### ISSUE THREAD

**Issue by davechez** [tiamo/spss#30]
The below code will create a .sav file that can be opened in SPSS. However, if I change the width from 255 to 256 the resulting file cannot be opened in SPSS.

```php
$data = [
    'header' => [
    ],
    'variables' => [
        [
            'name'       => 'TEST',
            'format'     => Variable::FORMAT_TYPE_A,
            'width'      => 255, // <- if this is 256 the .sav file cannot be opened
            'decimals'   => 0,
            'label'      => 'LABEL',
            'values'     => [],
            'missing'    => [],
            'columns'    => 15,
            'alignment'  => Variable::ALIGN_LEFT,
            'measure'    => Variable::MEASURE_NOMINAL,
            'attributes' => [
                '$@Role' => Variable::ROLE_INPUT,
            ],
            'data'       => ['test'],
        ],
    ]
];

$writer = new Writer($data);
$writer->save('test.sav');
```

If I try to open it, here is the SPSS error I'm getting:

GET 
  FILE='/\<path\>/test.sav'. 
 
\>Error.  Command name: GET FILE 
\>Invalid SPSS Statistics data file: /\<path\>/test.sav (DATA1204) 
\>Execution of this command stops. 
 
\>Error # 1405 in column 8.  Text: /\<path\>/test.sav 
\>Error when attempting to get a data file. 
DATASET NAME DataSet1 WINDOW=FRONT.

**Comment by imlcl** [comment]
@mennodekker Hi, this commit support writing string length longer than 255 ?

**Comment by mennodekker** [comment]
It should, at least in the unit test I wrote it all worked fine.
