### ISSUE TITLE
DATETIME fields can break subsequent numerical fields with value labels

### ISSUE THREAD

**Issue by meletis** [tiamo/spss#36]
I have the following input:

```
        $input = [
            'header'    => [
                'prodName'     => '@(#) SPSS DATA FILE - Example',
                'creationDate' => '25 Jul 19',
                'creationTime' => '21 07 49',
                'weightIndex'  => 0,
                'compression'  => 0,
            ],
            'variables' => [
                [
                    'alignment' => 1,
                    'attributes' => ['$@Role' => 3],
                    'columns' => 16,
                    'decimals' => 0,
                    'format' => 22,
                    'label' => "Interview date",
                    'measure' => 3,
                    'name' => "interview_date",
                    'width' => 20,
                    'data' => [
                        13783456875
                    ]
                ],
                [
                    'alignment' => 1,
                    'attributes' => ['$@Role' => 3],
                    'columns' => 10,
                    'decimals' => 0,
                    'format' => 5,
                    'label' => "Do you want to continue?",
                    'measure' => 3,
                    'name' => "consent",
                    'values' => [
                        0 => 'No',
                        1 => 'Yes'
                    ],
                    'width' => 9,
                    'data' => [
                        '1'
                    ]
                ]
            ]
        ];
```

The resulting .sav file make SPSS freeze for ever, it won't open.

There are two ways to make the file usable:

1. Reverse the variables. If the "consent" variable comes first, then everything is okay, the file will open just fine.

2. Remove the "values" (value labels) from the "consent" variable. Again, if those are removed, the file will open just fine.

My project's specs is such that I'm not allowed to reverse the order of the variables and I also need to support value labels, so could you please help me identify the problem?

**Comment by meletis** [comment]
I have narrowed down to the the "indexes" field of the ValueLabel class. It looks like the bug lies into this line (Writer.php, line 187):

```
$valueLabel->indexes = [$nominalIdx + 1];
```

**Comment by sakalauskas** [comment]
@meletis reproduced this as well and after a day of digging, I found what was causing this. 

When we have a date (date with a width of 20), it always shifts value labels by two spss variables as Utils::widthToOcts($var->width) would return 3. We do not see this issue this with regular numbers as usually Numeric field has a width of 8 and Utils::widthToOcts(8) returns 1. 

I believe the fix for this is to change https://github.com/tiamo/spss/blob/master/src/Sav/Writer.php#L204 to this:
```
if (Variable::isNumberFormat($var->format)) {
     $nominalIdx += 1;
} else {
     $nominalIdx += Utils::widthToOcts($var->width);
 }
``` 
@tiamo could you confirm that this is the solution to this problem?

**Comment by tiamo** [comment]
@sakalauskas done
