### ISSUE TITLE
extra string variables added when previous variable exceds 8 

### ISSUE THREAD

**Issue by arielgk** [tiamo/spss#38]
[data](http://spss.allenandunwin.com.s3-website-ap-southeast-2.amazonaws.com/Files/manipulate.zip
)![image](https://user-images.githubusercontent.com/10802010/62096800-41f73980-b25b-11e9-880a-179ceca067cb.png)

![image](https://user-images.githubusercontent.com/10802010/62097532-73710480-b25d-11e9-8aa0-817fd08c9ffa.png)

I think index 2 and 4,  shouldn't be there. or I'm missing something?
thanks

**Comment by lestcape** [comment]
@arielgk can you take a look if this pull: https://github.com/tiamo/spss/pull/51 solved your problem?

**Comment by tiamo** [comment]
fixed
