### ISSUE TITLE
PSPP can not read the generated sav file

### ISSUE THREAD

**Issue by lestcape** [tiamo/spss#46]
I'm using the example [write.php](https://github.com/tiamo/spss/blob/master/examples/write.php) from the master branch, to generate the file data.sav. When i try to open the file as it's generated in the [PSPP](https://www.gnu.org/software/pspp/) software (GNU pspp **version 1.0.1**), the file can not be opened and i received the following output:

warning: `/home/lestcape/Documentos/aaa/data.sav' near offset 0x18c: File
specifies unexpected value -1.79769e+308 (-0x1.fffffffffffbp+1023) as SYSMIS,
instead of -1.79769e+308 (-0x1.fffffffffffffp+1023).

warning: `/home/lestcape/Documentos/aaa/data.sav' near offset 0x18c: File
specifies unexpected value 1.79769e+308 (0x1.fffffffffffbp+1023) as HIGHEST,
instead of 1.79769e+308 (0x1.fffffffffffffp+1023).

warning: `/home/lestcape/Documentos/aaa/data.sav' near offset 0x18c: File
specifies unexpected value -1.79769e+308 (-0x1.fffffffffffbp+1023) as LOWEST,
instead of -1.79769e+308 (-0x1.ffffffffffffep+1023) or -1.79769e+308 (-0x1.
fffffffffffffp+1023).

error: `/home/lestcape/Documentos/aaa/data.sav' near offset 0xdc: Missing
string continuation record.

As most of warnings are related with the writer info i remove the comments for that session:
```php
        // 'info' => [
        //     'machineInteger' => [
        //         'machineCode' => 720,
        //         'version' => [23, 0, 0],
        //     ],
        //     'machineFloatingPoint' => [
        //         'sysmis' => -1.7976931348623157e+308,
        //         'highest' => 1.7976931348623157e+308,
        //         'lowest' => -1.7976931348623155e+308,
        //     ],
        // ],
```

The new resulting file is also not opened. I have not warnings now, but the error remaining and i get the following output after execute the example:

error: `/home/lestcape/Documentos/aaa/data.sav' near offset 0xdc: Missing
string continuation record.

**Note:**
When I remove the variable [bbbb_bbbbbb12](https://github.com/tiamo/spss/blob/master/examples/write.php#L51-L69) from the writer, the resulting data.sav file can be opened in pspp. So, the problem seem to be related with something there.

**Comment by lestcape** [comment]
Ok, i found the cause of this issue. Seem to be that we really need an empty record [here](
https://github.com/tiamo/spss/blob/master/src/Sav/Record/Variable.php#L167-L168).

**Comment by mennodekker** [comment]
You are right, and the next occurrence a few lines later should go.

**Comment by mennodekker** [comment]
I was the one who commented it out (Try the blame option to verify)
And I recently came to the same conclusion that is is needed there. I think SPSS is a little more foregiving so when I originally commented it out all still worked.

**Comment by lestcape** [comment]
Ok, i create a pull, to revert this then... Thanks.
