### ISSUE TITLE
Column format

### ISSUE THREAD

**Issue by mohd-aidi** [tiamo/spss#60]
Hi, i am a bit lost here. How can I get variable format in reader? for example I want to know if the data is datetime, string or numeric?

**Comment by lestcape** [comment]
Where `$index `is the index of the variable:

Variable Format Info:
`SPSS\Sav\Variable::getFormatInfo($savReader->variables[$index]->print[1]);`

Variable width:
`$savReader->variables[$index]->print[2];`

Variable decimal:
`$savReader->variables[$index]->print[3];`
